# Generated by Django 4.2.1 on 2023-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_task_description_task_file_alter_task_task_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
